set -g default-terminal "tmux-256color"

# So that we can select panes with the mouse and scroll the buffer as well.
set -g mouse on

# Rebind the prefix key to C-a, to match screen. Consider binding to C-Space
# instead to match our vim leader.
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Start windows and panes at 1, not 0, to align with keyboard number row.
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# With the vim-tmux-navigator plugin configures the prefix + hjkl to switch panes.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Shift arrow to switch windows.
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift+ctrl arrow to reorder windows.
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# ============================================================================
# Plugins to install with TPM.
# ============================================================================
# List of core plugins.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Status bar plugins.
set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'thewtex/tmux-mem-cpu-load'


# We manually install catpuccin, which otherwise is having name conflicts with tpm.
#set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Create a memory status bar module.
%hidden MODULE_NAME="memory"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󱀙 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_flamingo}"
set -ogqF "@catppuccin_${MODULE_NAME}_text" "#{ram_percentage}"

source "~/.config/tmux/plugins/catppuccin/tmux/utils/status_module.conf"


# For vim-style navigation (prefix + hjkl).
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"

set -agF status-right "#{E:@catppuccin_status_memory}"
# set -ag status-right "#[bg=#{@thm_flamingo},fg=#{@thm_crust}]#[reverse]#[noreverse]  "
# set -agF status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] ##{ram_percentage} "
# set -agF status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}] ##{ram_percentage}"
# set -ag status-right "#{E:@catppuccin_status_memory}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Supports saving and restoring tmux sessions between restarts.
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-processes 'ssh lazygit'
set -g @resurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
